pipeline {
	agent {
	  node {
	  label 'slave'
	  }
	}

	tools {
	  maven 'maven386'
	}
stages{
   stage("maven test"){
     steps{
	  sh ' mvn test'
	 }
   }
   stage("maven build"){
     steps{
	  sh 'mvn package'
	 }
   }
}



}
